config/routes.rb
Rails.application.routes.draw do
  root to: "sessions#index"
  get "/tuesday", to: "sessions#tuesday"
  get "/wednesday", to: "sessions#wednesday"
end

app/models/session.rb
class Session < ActiveRecord::Base
  belongs_to :track
  
  def start_time
    start.strftime("%I:%M %p")
  end

  def finish_time
    finish.strftime("%I:%M %p")
  end
end

app/models/track.rb
class Track < ActiveRecord::Base
  has_many :sessions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def index
    @sessions = Session.all
  end

  def tuesday
    @sessions = Session.where("start < ?", "9/12/2015")
  end

  def wednesday
    @sessions = Session.where("start > ?", "9/12/2015")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zerista</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="center container">
  <h4>Zerista</h4>
  <%= link_to "Tuesday", tuesday_path %>
  <%= link_to "Wednesday", wednesday_path %>
  <%= yield %>
</div>

</body>
</html>